# This file has been extracted from AMAPmod documentation (refermanual 18)

"""
FitTest
	Fit of a frequency distribution by a theoretical distribution.
  Usage
	Fit(histo, dist)	
  Arguments
	histo (histogram, mixture_data, convolution_data, compound_data),
	dist (distribution, mixture, convolution, compound).
	
  Returned Object
	No object returned.
  Description
	The result is displayed in the shell window (characteristics of the frequency and theoretical distributions, log-likelihood of the data for the theoretical distribution, information - maximum possible log-likelihood of the data -, c2 goodness of fit test).
	
  Background
	The difference between the information measure and the log-likelihood is the Kullback-Leibler divergence from the observed distribution to the theoretical distribution. It is also one-half the deviance of the theoretical distribution.
	
	Assume that a sample of size n is generated by a given random variable. The statistic  measures the random deviation between the observed frequencies fi and the theoretical frequencies npi:
	   with   
	If each theoretical frequency npi is greater than a given threshold (between 1 and 5 according to the authors),  has a c2 with k - 1 degrees of freedom.
"""
