# -*-python-*-

from openalea.sconsx import config, environ
import os

ALEASolution = config.ALEASolution
pj = os.path.join

options = Variables(['../options.py', 'options.py'], ARGUMENTS)
tools = ['qt4', 'bison', 'flex','install', 'vplants.tool']

env = ALEASolution(options, tools)

prefix = env['build_prefix']

# Build stage
SConscript(pj(prefix,"src/cpp/SConscript"), exports="env")
Default("build")
