# -*-python-*-

from openalea.sconsx import config, environ
import os

pj = os.path.join
ALEASolution = config.ALEASolution

options = Variables(['../options.py', 'options.py'], ARGUMENTS)

# Dependencies
WITHOUT_PLANTGL=True
if not WITHOUT_PLANTGL:
    common_tools = ['openalea.libmtg', 'openalea.plantgl', 'openalea.tool', 'openalea.amlobj',
                    'openalea.stattool', 'openalea.sequenceanalysis','boost_python']

    tools = ['python','flex','install', 'qt4', 'cgal'] + common_tools
else:
    common_tools = [ 'openalea.tool', 'openalea.amlobj',
                    'openalea.stattool', 'openalea.sequenceanalysis','boost_python']

    tools = ['python','flex', 'qt4', 'readline'] + common_tools

env = ALEASolution(options, tools)

# Build stage
prefix = env['build_prefix']
env.Append(LIBPATH=pj(prefix,'lib'))
SConscript(pj(prefix,"src/cpp/SConscript"),
           exports='env')
SConscript(pj(prefix,"src/wrapper/SConscript"),
           exports='env')

Default("build")
