/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
static yyconst short int yy_accept[363] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   80,   79,   78,   60,   58,    2,    3,   69,
       62,   32,   75,   57,   64,   31,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   76,   60,    1,    2,    3,   48,    2,    1,    2,
       61,   59,   70,   73,   62,   63,   64,   74,   72,   61,
        1,   62,    2,   71,   77,    2,    2,    3,   66,    0,
        0,   75,    0,    0,   65,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,

       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,    0,    1,    0,    2,    3,    3,    3,   48,    2,
        2,    2,   77,    2,    0,    0,   68,    0,    0,   67,
       76,   76,   76,   76,   76,    0,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   36,
       76,   76,   76,   30,    0,   54,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,    0,    0,    0,    0,    0,    0,    0,   76,   76,
       76,    4,   76,   76,    0,   76,   76,   76,   49,   52,
       76,   76,   76,   76,   21,   76,   76,   76,   27,   76,

       76,    0,   34,   22,   76,   50,   76,   39,   76,   76,
       76,   76,   76,   76,   76,   56,   35,    0,    0,    0,
        0,   37,   76,   76,   76,   76,   40,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   42,
       76,   76,   76,   28,    9,   47,   76,   76,   53,    0,
        0,    0,    0,   76,   76,   76,   76,    0,    0,   76,
       76,   76,   76,   76,   76,    5,    6,   76,   76,   76,
       13,   51,   76,   76,   76,   38,    8,    0,    0,    0,
        0,   76,    7,   76,   76,    0,    0,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   29,   15,

        0,   14,    0,   76,   76,   76,    0,   41,   76,   76,
       76,   76,   24,   33,   45,   25,   76,   76,   76,    0,
        0,   76,   19,   76,    0,    0,   76,   76,   76,   76,
       76,   76,   76,    0,    0,   46,   76,   43,    0,   76,
       12,   76,   76,   11,   76,   16,    0,    0,   23,    0,
       76,   26,   55,   76,   18,   17,    0,   76,   20,   44,
       10,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    6,    1,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
        1,    1,   18,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   28,   29,   30,   31,   32,   33,
       28,   34,   35,   36,   37,   38,   28,   39,   40,   28,
        1,    1,    1,   41,   42,    1,   43,   44,   28,   28,

       45,   28,   46,   47,   48,   28,   28,   49,   50,   51,
       28,   28,   28,   28,   28,   52,   28,   28,   28,   28,
       28,   28,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    2,    2,    3,    4,    1,    1,    1,    1,    5,
        1,    6,    5,    5,    6,    1,    1,    1,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    5
    } ;

static yyconst short int yy_base[373] =
    {   0,
        0,    0,    0,   52,   56,   60,  113,  166,   79,   56,
      219,  272,  578,  579,  579,  579,  579,   81,    0,  579,
       57,  579,  562,  579,   59,  579,   45,    0,   48,   64,
       59,   65,  553,   61,  112,   74,  114,  538,   52,  164,
       62,    0,  138,  579,  145,  157,    0,   91,  579,  190,
      579,  579,  579,  579,   90,  579,  139,  579,  579,  209,
      579,  579,  133,  579,  521,  229,  134,    0,  579,  168,
      563,  557,  170,  554,  579,    0,  537,  536,  549,  114,
      553,  194,  514,  522,  528,  530,  543,  527,  537,  527,
      525,  129,  533,  525,  504,  515,  539,  527,  521,   70,

      527,  515,  134,  523,  528,  527,  511,  514,  500,  509,
      508,  242,  579,  246,  250,  254,  261,  265,    0,  185,
      282,  238,  487,  306,  512,  501,  579,  510,  499,  579,
      509,  511,  498,  509,  171,  501,  498,  502,  507,  482,
      476,  498,  495,  487,  492,  498,  490,  490,  495,    0,
      481,  493,  469,    0,  474,    0,  490,  489,  490,  461,
      486,  479,  471,  480,  476,  471,  476,  482,  449,  468,
      476,  317,  324,  328,  467,  463,  465,  461,  475,  474,
      457,    0,  468,  467,  459,  458,  456,  452,    0,    0,
      449,  457,  446,  470,    0,  458,  453,  440,    0,  459,

      425,  436,    0,    0,  443,    0,  445,    0,  433,  436,
      448,  447,  438,  436,  422,    0,    0,  443,  442,  441,
      440,    0,  428,  438,  439,  438,  227,  425,  430,  429,
      415,  433,  419,  273,  416,  430,  431,  415,  401,  579,
      416,  419,  412,    0,    0,    0,  419,  414,    0,  423,
      412,  421,  410,  419,  402,  400,  398,  398,  385,  389,
      384,  386,  395,  353,  356,    0,    0,  344,  349,  339,
        0,    0,  343,  342,  349,    0,    0,  337,  342,  334,
      340,  335,    0,  342,  328,  336,  322,  326,  333,  322,
      336,  320,  320,  314,  317,  325,  328,  327,    0,  579,

      318,  579,  317,  326,  324,  318,  314,  331,  315,  309,
      313,  307,    0,    0,    0,    0,  306,  316,  317,  311,
      301,  300,    0,  279,  293,  279,  276,  275,  273,  282,
      271,  265,  266,  279,  278,    0,  273,  579,  267,  244,
        0,  230,  217,    0,  194,    0,  175,  171,    0,  166,
      156,    0,    0,  142,  579,  579,   88,   77,    0,  579,
        0,  579,  381,  387,  393,  399,  405,   62,  411,  417,
      421,  427
    } ;

static yyconst short int yy_def[373] =
    {   0,
      363,  363,  362,    3,  364,  364,  365,  365,    8,    8,
      366,  366,  362,  362,  362,  362,  362,  362,  367,  362,
      362,  362,  362,  362,  362,  362,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  362,  362,  362,  369,  370,  370,  362,  370,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  371,  362,  371,  371,  362,  367,  362,  362,
      362,  362,  362,  362,  362,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  362,  362,  372,  362,  369,  369,  369,  370,  370,
      370,  371,  371,  371,  362,  362,  362,  362,  362,  362,
      368,  368,  368,  368,  368,  362,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  362,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  372,  372,  372,  362,  362,  362,  362,  368,  368,
      368,  368,  368,  368,  362,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  362,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  362,  362,  362,
      362,  368,  368,  368,  368,  368,  362,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  362,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  362,
      362,  362,  362,  368,  368,  368,  368,  362,  362,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  362,  362,  362,
      362,  368,  368,  368,  368,  362,  362,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  362,

      362,  362,  362,  368,  368,  368,  362,  362,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  362,
      362,  368,  368,  368,  362,  362,  368,  368,  368,  368,
      368,  368,  368,  362,  362,  368,  368,  362,  362,  368,
      368,  368,  368,  368,  368,  368,  362,  362,  368,  362,
      368,  368,  368,  368,  362,  362,  362,  368,  368,  362,
      368,    0,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362
    } ;

static yyconst short int yy_nxt[633] =
    {   0,
       15,   16,   17,   18,   19,   20,   15,   15,   15,   21,
       22,   15,   15,   15,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   28,   34,   28,   35,   36,
       37,   28,   38,   39,   40,   41,   28,   28,   28,   28,
       15,   42,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   18,   43,   44,   45,   46,   16,   14,   18,
       19,   43,   49,   45,   46,   62,   69,   76,   70,   71,
       73,   74,   15,   77,  103,   75,   79,   78,  104,   80,
       51,   52,   18,   19,   67,   81,   82,   87,   62,   85,
       91,   92,   96,  110,   67,   15,   88,   86,   89,   69,

      158,  111,   71,   97,   45,  159,   83,  361,   48,   98,
      360,   84,   50,   15,   51,   52,   18,   19,   15,   53,
       15,   54,   55,   15,   15,   15,   56,   23,   24,   57,
       15,   18,   99,   67,   93,  134,  122,   67,   94,  112,
      113,  112,  114,  120,  135,  100,  112,  113,  115,  114,
      149,   74,  162,   59,   15,   75,   95,  101,  112,  113,
      117,  118,  163,  359,  150,   18,   15,   60,   61,   45,
       46,   15,   53,   15,   54,   55,   15,   15,   15,   56,
       23,   24,   57,   15,  105,   67,   67,  358,   67,  106,
      112,  112,  113,  115,  114,  357,  125,  115,  128,  107,

      126,  183,  129,  108,  356,  184,   59,   15,  355,  117,
      112,  113,  112,  114,  137,  109,  354,  138,   45,   15,
       51,   52,   63,   19,   15,   15,   64,   15,  139,   15,
      112,  113,  124,  114,   15,   15,   15,  120,  258,  353,
      259,  122,  121,  112,  113,  112,  114,  112,  113,  173,
      174,  112,  113,  115,  114,  112,  113,  117,  118,   15,
      352,  112,  112,  113,  117,  118,  112,  113,  117,  118,
      351,   18,   15,   60,   61,   66,   46,   15,   15,   64,
       15,  115,   15,  112,  113,  115,  114,   15,   15,   15,
       67,  266,  267,  350,  112,  349,  348,  347,  173,  346,

      345,  344,  115,  343,  342,  341,  117,  112,  113,  124,
      114,  340,   15,  117,  339,  338,  337,  117,  112,  113,
      173,  174,  336,  335,   45,  112,  113,  173,  174,  112,
      113,  173,  174,  334,  121,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  115,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  173,
      300,  299,  298,  297,  296,  295,  173,  294,  293,  292,
      173,   14,   14,   14,   14,   14,   14,   47,   47,   47,
       47,   47,   47,   58,   58,   58,   58,   58,   58,   65,

       65,   65,   65,   65,   65,   68,  291,   68,   68,   68,
       68,  116,  116,  116,  116,  116,  116,  119,  290,  289,
      288,  119,  119,  123,  287,  123,  123,  172,  172,  172,
      172,  172,  172,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  265,  264,  263,  262,  261,  260,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,

      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  182,  181,  180,  179,  178,  177,  176,  175,  362,
      171,  170,  169,  168,  167,  166,  165,  164,  161,  160,
      157,  156,  155,  154,  153,  152,  151,  148,  147,  146,
      145,  144,  143,  142,  141,  140,  136,  133,  132,  131,
      130,   72,  127,  362,  102,   90,   72,  362,   13,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362
    } ;

static yyconst short int yy_chk[633] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    5,    5,    5,
        5,    6,    6,    6,    6,   10,   21,  368,   21,   21,
       25,   25,   10,   27,   39,   25,   29,   27,   39,   29,
        9,    9,    9,    9,   18,   30,   30,   32,    9,   31,
       34,   34,   36,   41,   48,    9,   32,   31,   32,   55,

      100,   41,   55,   36,    4,  100,   30,  358,    5,   36,
      357,   30,    6,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    9,   37,   18,   35,   80,   63,   67,   35,   43,
       43,   43,   43,   48,   80,   37,   45,   45,   45,   45,
       92,   57,  103,    7,    7,   57,   35,   37,   46,   46,
       46,   46,  103,  354,   92,    7,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,   40,   63,   67,  351,  120,   40,
       43,   50,   50,   50,   50,  350,   70,   45,   73,   40,

       70,  135,   73,   40,  348,  135,    8,    8,  347,   46,
       60,   60,   60,   60,   82,   40,  345,   82,    8,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   82,   11,
       66,   66,   66,   66,   11,   11,   11,  120,  227,  343,
      227,  122,   50,  112,  112,  112,  112,  114,  114,  114,
      114,  115,  115,  115,  115,  116,  116,  116,  116,   11,
      342,   60,  117,  117,  117,  117,  118,  118,  118,  118,
      340,   11,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   66,   12,  121,  121,  121,  121,   12,   12,   12,
      122,  234,  234,  339,  112,  337,  335,  334,  114,  333,

      332,  331,  115,  330,  329,  328,  116,  124,  124,  124,
      124,  327,   12,  117,  326,  325,  324,  118,  172,  172,
      172,  172,  322,  321,   12,  173,  173,  173,  173,  174,
      174,  174,  174,  320,  121,  319,  318,  317,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  301,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  124,  289,
      288,  287,  286,  285,  284,  282,  281,  280,  279,  172,
      278,  275,  274,  273,  270,  269,  173,  268,  265,  264,
      174,  363,  363,  363,  363,  363,  363,  364,  364,  364,
      364,  364,  364,  365,  365,  365,  365,  365,  365,  366,

      366,  366,  366,  366,  366,  367,  263,  367,  367,  367,
      367,  369,  369,  369,  369,  369,  369,  370,  262,  261,
      260,  370,  370,  371,  259,  371,  371,  372,  372,  372,
      372,  372,  372,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  248,  247,  243,  242,  241,  239,  238,  237,
      236,  235,  233,  232,  231,  230,  229,  228,  226,  225,
      224,  223,  221,  220,  219,  218,  215,  214,  213,  212,
      211,  210,  209,  207,  205,  202,  201,  200,  198,  197,
      196,  194,  193,  192,  191,  188,  187,  186,  185,  184,
      183,  181,  180,  179,  178,  177,  176,  175,  171,  170,

      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  155,  153,  152,  151,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  139,  138,  137,
      136,  134,  133,  132,  131,  129,  128,  126,  125,  123,
      111,  110,  109,  108,  107,  106,  105,  104,  102,  101,
       99,   98,   97,   96,   95,   94,   93,   91,   90,   89,
       88,   87,   86,   85,   84,   83,   81,   79,   78,   77,
       74,   72,   71,   65,   38,   33,   23,   13,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
/* -*-c++-*-
 *  ----------------------------------------------------------------------------
 *
 *       AMAPmod: Exploring and Modeling Plant Architecture
 *
 *       Copyright 1995-2000 UMR Cirad/Inra Modelisation des Plantes
 *
 *       File author(s): Ch. Godin (christophe.godin@cirad.fr)
 *
 *       $Source$
 *       $Id: scanner.l 3263 2007-06-06 14:07:06Z dufourko $
 *
 *       Forum for AMAPmod developers    : amldevlp@cirad.fr
 *
 *  ----------------------------------------------------------------------------
 *
 *                      GNU General Public Licence
 *
 *       This program is free software; you can redistribute it and/or
 *       modify it under the terms of the GNU General Public License as
 *       published by the Free Software Foundation; either version 2 of
 *       the License, or (at your option) any later version.
 *
 *       This program is distributed in the hope that it will be useful,
 *       but WITHOUT ANY WARRANTY; without even the implied warranty of
 *       MERCHANTABILITY or FITNESS For A PARTICULAR PURPOSE. See the
 *       GNU General Public License for more details.
 *
 *       You should have received a copy of the GNU General Public
 *       License along with this program; see the file COPYING. If not,
 *       write to the Free Software Foundation, Inc., 59
 *       Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 *  ----------------------------------------------------------------------------
 */




#include <iostream>
#include <string>
#ifdef SYSTEM_IS__IRIX
#include <values.h>
#else
#include <float.h>
#define MINFLOAT FLT_MIN
#define MAXFLOAT FLT_MAX
#endif
#include "tool/config.h"

#include "aml/defs.h"

#include "parser_dec.h"
#ifdef BISON_HPP
#include "parser.hpp"
#else
#include "parser.cpp.h"
#endif

static const char rcsid[] = "$Id: scanner.l 3263 2007-06-06 14:07:06Z dufourko $";

#ifdef _WIN32
extern "C" {
  int isatty (int handle);
}

#define YY_SKIP_YYWRAP
int yywrap() {
  return 1;
}

#endif

#if 0

#define SCANNERDEBUG

#if 1
#define SIMPIFIEDSCANNERDEBUG
#endif

#endif

#ifdef SCANNERDEBUG
#define STATE(x)
#else
#define STATE(x)
#endif


#ifdef SCANNERDEBUG

#ifndef SIMPIFIEDSCANNERDEBUG

static void TraceTok(char* s, char* t) {

  if (s[0] == '\n') std::cerr << "[eol<" << t << ">]" << std::flush;
  else std::cerr << "[" << s << "<" << t << ">]" << std::flush;

  if (strcmp(s,"eol") == 0) std::cerr << std::endl;
  else if (strcmp(s,"wln") == 0) std::cerr << std::endl;

}

#else

static void TraceTok(char* s) {

  if (s[0] == '\n') std::cerr << "[eol]" << std::flush;
  else std::cerr << "[" << s << "]" << std::flush;

  if (strcmp(s,"eol") == 0) std::cerr << std::endl;
  else if (strcmp(s,"wln") == 0) std::cerr << std::endl;

}

#endif

static void Trace(char* s) {

  std::cerr << "(" << s << ")" << std::flush;

  if (strcmp(s,"eol") == 0) std::cerr << std::endl;
  else if (strcmp(s,"wln") == 0) std::cerr << std::endl;

}

#ifndef SIMPIFIEDSCANNERDEBUG
static void PrintLineNb() {
  std::cerr << "\nLINENB " << linenb << " :"<< std::endl;
}
#else
#define PrintLineNb()
#endif

#else

#ifdef SIMPIFIEDSCANNERDEBUG
#define TraceTok(s)
#else
#define TraceTok(s,t)
#endif

#define Trace(s)
#define PrintLineNb()

#endif

#ifdef SIMPIFIEDSCANNERDEBUG
#define TRACE(t) cat_curr_line_buf();TraceTok(yytext)
#else
#define TRACE(t) cat_curr_line_buf();TraceTok(yytext, t)
#endif

static int linenb = 1;
static int colnb = 1;
static int previous_colnb = 1;

static int previous_state = YY_START;

static char curr_line_buf[MAXLINELENGTH] = {'\0'};
static char prev_line_buf[MAXLINELENGTH] = {'\0'};

static void cat_curr_line_buf();
static void reset_curr_line_buf();

static MTGCode mtg_code;

#define YY_USER_ACTION  previous_state = YY_START; // current state of the scanner

#define START 1
#define FILENAME 2
#define CODE_A 3
#define CODE_B 4
#define MTGFEATURE 5


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 187 "scanner.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 363 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 579 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 189 "scanner.l"
{Trace("wln");reset_curr_line_buf();linenb++;colnb=1;PrintLineNb();}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 190 "scanner.l"
{Trace("wsc");cat_curr_line_buf();}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 191 "scanner.l"
{Trace("comment");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 193 "scanner.l"
{TRACE("TokCODE"); return(TokCODE);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 194 "scanner.l"
{TRACE("TokFORM_A"); mtg_code = FORM_A; return(TokFORM_A);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 195 "scanner.l"
{TRACE("TokFORM_B"); mtg_code = FORM_B; return(TokFORM_B);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 197 "scanner.l"
{TRACE("TokCLASSES"); return(TokCLASSES);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 198 "scanner.l"
{TRACE("TokSYMBOL"); return(TokSYMBOL);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 199 "scanner.l"
{TRACE("TokSCALE"); return(TokSCALE);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 200 "scanner.l"
{TRACE("TokVDECOMP"); return(TokVDECOMP);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 201 "scanner.l"
{TRACE("TokINDEXATION"); return(TokINDEXATION);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 202 "scanner.l"
{TRACE("TokVDEF"); return(TokVDEF);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 203 "scanner.l"
{TRACE("TokLINEAR"); yylval.intval = LINEAR; return(TokInteger);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 204 "scanner.l"
{TRACE("TokLESSLINEAR"); yylval.intval = LESSLINEAR; return(TokInteger);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 205 "scanner.l"
{TRACE("TokPLUSLINEAR"); yylval.intval = PLUSLINEAR; return(TokInteger);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 206 "scanner.l"
{TRACE("TokPURELINEAR"); yylval.intval = PURELINEAR; return(TokInteger);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 207 "scanner.l"
{TRACE("TokLESSPURELINEAR"); yylval.intval = LESSPURELINEAR; return(TokInteger);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 208 "scanner.l"
{TRACE("TokPLUSPURELINEAR"); yylval.intval = PLUSPURELINEAR; return(TokInteger);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 209 "scanner.l"
{TRACE("TokCONNECTED"); yylval.intval = CONNECTED; return(TokInteger);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 210 "scanner.l"
{TRACE("TokNOTCONNECTED"); yylval.intval = NOTCONNECTED; return(TokInteger);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 211 "scanner.l"
{TRACE("TokFREE"); yylval.intval = FREE_D; return(TokInteger);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 212 "scanner.l"
{TRACE("TokNONE"); yylval.intval = NONE_D; return(TokInteger);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 213 "scanner.l"
{TRACE("TokCONSECUTIVE"); yylval.intval = CONSECUTIVE; return(TokInteger);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 214 "scanner.l"
{TRACE("TokEXPLICIT"); yylval.intval = EXPLICIT; return(TokInteger);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 215 "scanner.l"
{TRACE("TokIMPLICIT"); yylval.intval = IMPLICIT; return(TokInteger);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 217 "scanner.l"
{TRACE("TokDESCRIPTION"); return(TokDESCRIPTION);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 218 "scanner.l"
{TRACE("TokLEFT"); return(TokLEFT);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 219 "scanner.l"
{TRACE("TokRIGHT"); return(TokRIGHT);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 220 "scanner.l"
{TRACE("TokRELTYPE"); return(TokRELTYPE);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 221 "scanner.l"
{TRACE("TokMAX"); return(TokMAX);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 222 "scanner.l"
{TRACE("TokInteger"); yylval.intval = MAXINT; return(TokInteger);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 223 "scanner.l"
{TRACE(","); return(',');}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 225 "scanner.l"
{TRACE("TokFEATURES"); return(TokFEATURES);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 226 "scanner.l"
{TRACE("TokFNAME"); return(TokFNAME);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 227 "scanner.l"
{TRACE("TokFTYPE"); return(TokFTYPE);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 228 "scanner.l"
{TRACE("TokFType"); yylval.ftypeval = INTEGER; return(TokFType);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 229 "scanner.l"
{TRACE("TokFType"); yylval.ftypeval = ALPHA; return(TokFType);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 230 "scanner.l"
{TRACE("TokFType"); yylval.ftypeval = ALPHA; return(TokFType);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 231 "scanner.l"
{TRACE("TokFType"); yylval.ftypeval = REAL; return(TokFType);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 232 "scanner.l"
{TRACE("TokFType"); yylval.ftypeval = DDMM; return(TokFType);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 233 "scanner.l"
{TRACE("TokFType"); yylval.ftypeval = DDMMYY; return(TokFType);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 234 "scanner.l"
{TRACE("TokFType"); yylval.ftypeval = MMYY; return(TokFType);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 235 "scanner.l"
{TRACE("TokFType"); yylval.ftypeval = DDMMTIME; return(TokFType);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 236 "scanner.l"
{TRACE("TokFType"); yylval.ftypeval = DDMMYYTIME; return(TokFType);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 238 "scanner.l"
{TRACE("TokFType"); BEGIN FILENAME; yylval.ftypeval = GEOMETRY; return(TokFType);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 239 "scanner.l"
{TRACE("TokFType"); BEGIN FILENAME; yylval.ftypeval = APPEARANCE; return(TokFType);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 240 "scanner.l"
{TRACE("TokFType"); BEGIN FILENAME; yylval.ftypeval = GENERIC; return(TokFType);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 242 "scanner.l"
{TRACE("TokFilename"); BEGIN START; sprintf(yylval.stgval,"%s",yytext); return(TokFilename);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 244 "scanner.l"
{TRACE("TokDate"); sprintf(yylval.stgval,"%s",yytext); return(TokString);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 245 "scanner.l"
{TRACE("TokNbEl"); sprintf(yylval.stgval,"%s",yytext); return(TokString);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 246 "scanner.l"
{TRACE("TokLength"); sprintf(yylval.stgval,"%s",yytext); return(TokString);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 247 "scanner.l"
{TRACE("TokDiam"); sprintf(yylval.stgval,"%s",yytext); return(TokString);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 248 "scanner.l"
{TRACE("TokState"); sprintf(yylval.stgval,"%s",yytext); return(TokString);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 250 "scanner.l"
{TRACE("TokMTG"); return(TokMTG);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 251 "scanner.l"
{TRACE("TokENTITYCODE"); return(TokENTITYCODE);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 252 "scanner.l"
{TRACE("TokENTITYCODE"); return(TokENTITYCODE);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 254 "scanner.l"
{TRACE(":"); return(':');}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 255 "scanner.l"
{TRACE("eol");linenb++;previous_colnb = colnb; colnb=1;reset_curr_line_buf();PrintLineNb();return eol;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 256 "scanner.l"
{TRACE("eol");linenb++;previous_colnb = colnb; colnb=1;reset_curr_line_buf();PrintLineNb(); startCodeState();return eol;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 257 "scanner.l"
{TRACE("tab");previous_colnb = colnb; colnb++;return tabc;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 258 "scanner.l"
{TRACE("tab");previous_colnb = colnb; colnb++; if (colnb>=firstFeatCol() && firstFeatCol() != -1) startFeatureState();return tabc;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 259 "scanner.l"
{TRACE("TokReltype"); yylval.etypeval = &PLUS; return(TokReltype);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 260 "scanner.l"
{TRACE("TokReltype"); yylval.etypeval = &SLASH; return(TokReltype);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 261 "scanner.l"
{TRACE("TokReltype"); yylval.etypeval = &LESS; return(TokReltype);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 262 "scanner.l"
{TRACE("TokReltype"); yylval.etypeval = &LESSLESS; return(TokReltype);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 263 "scanner.l"
{TRACE("TokReltype"); yylval.etypeval = &PLUSPLUS; return(TokReltype);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 264 "scanner.l"
{TRACE("TokReltype"); yylval.etypeval = &LESSDOTLESS; return(TokReltype);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 265 "scanner.l"
{TRACE("TokReltype"); yylval.etypeval = &PLUSDOTPLUS; return(TokReltype);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 266 "scanner.l"
{TRACE("TokSymbol"); yylval.charval = yytext[0]; return TokSymbol;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 268 "scanner.l"
{TRACE("("); startFeatureState(); return('(');}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 269 "scanner.l"
{TRACE(")"); startCodeState(); return(')');}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 270 "scanner.l"
{TRACE("^"); return('^');}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 271 "scanner.l"
{TRACE("*"); return('*');}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 272 "scanner.l"
{TRACE("TokSymbol"); yylval.charval = yytext[0]; return TokSymbol;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 273 "scanner.l"
{TRACE("TokInteger"); yylval.intval = atoi(yytext); return(TokInteger);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 275 "scanner.l"
{TRACE("TokString"); sprintf(yylval.stgval,"%s",yytext); return(TokString);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 276 "scanner.l"
{TRACE("TokString"); sprintf(yylval.stgval,"%s",yytext); return(TokString);}
	YY_BREAK
case YY_STATE_EOF(CODE_A):
case YY_STATE_EOF(CODE_B):
case YY_STATE_EOF(MTGFEATURE):
#line 277 "scanner.l"
{/*cerr << "<<EOF>>" << std::endl;*/ yyterminate();}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 279 "scanner.l"
{TRACE("ReadError");return TokError;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 281 "scanner.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(START):
case YY_STATE_EOF(FILENAME):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 53);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 363 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 53;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 363 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 362);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 281 "scanner.l"


void startStartState() {

#ifdef SCANNERDEBUG
  std::cerr << "{START}";
#endif

  BEGIN START;

}

void startFeatureState() {

#ifdef SCANNERDEBUG
  std::cerr << "{FEATURE}";
#endif

  BEGIN MTGFEATURE;

}

void startCodeState() {

  switch(mtg_code) {
  case FORM_A:
    BEGIN CODE_A;
#ifdef SCANNERDEBUG
    std::cerr << "{CODE_A}";
#endif
    break;
  case FORM_B:
    BEGIN CODE_B;
#ifdef SCANNERDEBUG
    std::cerr << "{CODE_B}";
#endif
    break;
  }

}

const char* yyText() {

  return yytext;

}

int yyLineNb() {

  return linenb;

}

int yyColumnNb() {

  return colnb;

}

int yyPreviousColumnNb() {

  return previous_colnb;

}

const char* yyCurrentLine() {

  return curr_line_buf;

}

const char* yyPreviousLine() {

  return prev_line_buf;

}

int yyTokenLength() {

  return yyleng;

}

static void cat_curr_line_buf() {

  if (yytext[0] != '\n')
  if (strlen(curr_line_buf) + strlen(yytext) < MAXLINELENGTH) strcat(curr_line_buf, yytext);
}

static void reset_curr_line_buf() {

  //  cerr << "line# " << yyLineNb()-1 << ":\t" << curr_line_buf << endl;

  strcpy(prev_line_buf, curr_line_buf);
  curr_line_buf[0] = '\0';

}

static void lexunput(char c) {

  // after unputting a '\n' the prev_line_buf is nolonger OK
  // should not be used
  if (c == '\n')  {
#ifdef SCANNERDEBUG
    fprintf(stderr,"<^\\n>");
#endif
    strcpy(curr_line_buf, prev_line_buf);
  }
  if (c == '\t')  {
#ifdef SCANNERDEBUG
    fprintf(stderr,"<^\t>");
#endif
    if (strlen(curr_line_buf)) {curr_line_buf[strlen(curr_line_buf)-1] = '\0';}
  }
  else {
#ifdef SCANNERDEBUG
    fprintf(stderr,"<^%c>", curr_line_buf[strlen(curr_line_buf)-1]);
#endif
    if (strlen(curr_line_buf)) {curr_line_buf[strlen(curr_line_buf)-1] = '\0';}
  }

  unput(c);
}

/* La fonction unput(char c) ne gere pas un index sur le fichier ouvert
   mais tamponne les caracteres recu dans un buffer special 'yysbuf'.
   Ceci permet de faire unput(c) sur des carcateres n'appartenant pas
   au fichier original; input tient compte de ce buffer pour sortir
   des caracteres.

*/

void yyUnputToken() {

  register int i;
  for(i=yyleng-1;i>=0;i--) lexunput(yytext[i]);

  // recover the scanner state before analysing this token

  switch(previous_state) {

  case START:
    startStartState();
    break;
  case CODE_A:
  case CODE_B:
    startCodeState();
    break;
  case MTGFEATURE:
    startFeatureState();
    break;

  }

}

/* Lex ATT ne sait pas se reinitialiser tout seul */

void lexAbort() {

  startStartState();

  yyrestart(yyin); // In case the parser abort while the scanner still proceeds

  linenb = 1;
  colnb = 1;

}



