# -*-python-*-

from openalea.sconsx import config, environ
import os

Config = config.Config
ALEAConfig = config.ALEAConfig
ALEAEnvironment = config.ALEAEnvironment

pj = os.path.join

name = 'mtg'

SConsignFile()

options = Options(['../options.py', 'options.py'], ARGUMENTS)

# Dependencies
tools = ['flex', 'bison','qt4', 'opengl', 'plantgl', 'vplants.amlobj', 'vplants.tool']

# Set all the common options for the package
# Fill the options from file option.py or cmd line args.
env = Environment(options=options)
conf= ALEAConfig(name, tools)
conf.UpdateOptions(options)
options.Update(env)
conf.Update(env)

# Generate Help available with the cmd scons -h
Help(options.GenerateHelpText(env))

# Set build directory
prefix = env['build_prefix']
BuildDir(prefix, '.')

env.Prepend(CPPPATH='$build_includedir')
env.Prepend(LIBPATH='$build_libdir')

# Build stage
SConscript(pj(prefix,"src/cpp/SConscript"), exports="env")

Default("build")
