# -*-python-*-

from openalea.sconsx import config, environ
import os

pj = os.path.join
ALEASolution = config.ALEASolution

options = Options(['../options.py', 'options.py'], ARGUMENTS)
tools = ['flex', 'bison','qt4', 'opengl', 'vplants.plantgl', 'vplants.amlobj', 'vplants.tool']

env = ALEASolution(options, tools)

prefix = env['build_prefix']

# Build stage
SConscript(pj(prefix,"src/cpp/SConscript"), exports="env")

Default("build")
