# -*-python-*-

from openalea.sconsx import config, environ
import os

pj = os.path.join
ALEASolution = config.ALEASolution

options = Variables(['../options.py', 'options.py'], ARGUMENTS)
tools = ['flex', 'bison','qt4', 'opengl', 'boost_python', 'vplants.tool', 'vplants.plantgl', 'vplants.amlobj']

env = ALEASolution(options, tools)

prefix = env['build_prefix']

# Build stage
SConscript(pj(prefix,"src/cpp/SConscript"), exports="env")

Default("build")
